analyzers:
  disable:
    - mixedcaps # disable mixedcaps analyzer. because the underscores analyzer is more detailed.
analyzers-settings:
  getters:
    exclude:
      - GetCertificate
      - GetUpstream
  ifacenames:
    all: true
  repetition:
    exclude:
      - upstream
      - urlstr
  varnames:
    small-varname-max: 4       # max length of variable name for small scope (default: -1)
    medium-varname-max: 10     # max length of variable name for medium scope (default: -1)
    large-varname-max: 16      # max length of variable name for large scope (default: -1)
    very-large-varname-max: 32 # max length of variable name for very large scope (default: -1)
